services:
  - type: web
    name: web-crawler-demo
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: CRAWLER_DELAY
        value: 1.0
      - key: RESPECT_ROBOTS
        value: true
      - key: PYTHONPATH
        value: .
      - key: USE_FALLBACK
        value: true
    plan: free
